algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

nota: real

inicio

escreva ("Digite a sua nota: ")
leia(nota)
se (nota >= 7) entao
escreval("Você foi aprovado.")
senao
escreval("Você foi reprovado.")
fimse

fimalgoritmo