algoritmo "atividade17"


var

numero: inteiro

inicio


escreva("Digite um número: ")
leia(numero)

se (numero < 0) entao
escreva("O número é negativo: ")

senao 
    se (numero = 0) ent
escreva("O número é neutro")

senao 
    se(numero > 100 E numero > 0 ) entao
escreva("O número é postivo e maior 100")

senao
    se(numero > 0 E numero < 100) entao
escreva("O número é positivo e menor que 100") 

senao 
escreva("Você digitou o número 100") 

fimse 
fimse 
fimse
fimse




fimalgoritmo