algoritmo "atividade13"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

idade: inteiro

inicio

escreva ("Digite sua idade: ")
leia(idade)

se (idade>= 18) entao
escreval("Você é maior de idade.")
senao
escreval("Você é menor de idade.")
fimse

fimalgoritmo