algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

numero: inteiro

inicio
escreva("Digite um número: ")
leia(numero)

se ( numero >=5) entao
escreval ("Esse número é maior que cinco")
senao
escreval ("Esse número é menor que cinco")
fimse

fimalgoritmo